title: Hillspire Apex Style Guide
email: amorris@hillspire.com
description: > # Defines an open source set of coding standards for the Apex programming language.
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: UA-92989768-2